- name: Demo on vars
  hosts: localhost
  vars:
    URL_PLAY: play.example.com
  tasks:
    - name: Print variable
      ansible.builtin.debug:
        msg: URL_PLAY - {{ URL_PLAY }}
    - name: Task variable
      ansible.builtin.debug:
        msg: URL_TASK - {{ URL_TASK }}
      vars:
        URL_TASK: tasks.example.com


#play level variables can be acessed by all the tasks and roles
#task level variable can be accessed by only task
#role level variable is accessible in that role tasks
#variable from CLI IS having higher precedencies of any variable

#IMP: if the value of any key is variable then double quote it
#ex: msg: {{URL}}, THIS NEEDS TO BE GIVEN AS msg: "{{URL}}"
